#LogIn Locator
LoginUsernameInputBox = "//input[@id=':r399:']"
LoginPasswordInputBox = "//input[@id=':r39b:']"
LoginButton = "//button[@id=':r39d:']"
#Main page Locator
LoginLink = "//*[@id='root']/div/div[1]/div/div[1]/div[2]/div/a[1]"
SignupLink = "//*[@id='root']/div/div[1]/div/div[1]/div[2]/div/a[2]"
Profile = "//*[@id='root']/div/div[1]/div/div[1]/div[2]/div[2]/div/p"
LogoutButtonAdmin = "//*[@id='account-menu']/div[3]/ul/li[4]"
LogoutButtonUser = "//*[@id='account-menu']/div[3]/ul/li[3]"
MainPageProduct = "//*[@id='root']/div/div[2]/div[2]/div/div[3]/div[1]/a[1]/div[2]"
CartIcon = "//*[@id='root']/div/div[1]/div/div[2]/div[2]/a/span/span"
SeeCartButton = "//*[@id='root']/div/div[1]/div/div[2]/div[2]/div/div[2]/a/button"
SearchBar = "//*[@id='root']/div/div[1]/div/div[2]/div[1]/div/div"
#SignUp Locator
SignupFullnameInputBox = "//*[@id='root']/div/div/div[2]/div/div/div[2]/div[2]/div/form/div[1]/div/div"
SignupRadioMale = "//input[@value='0']"
SignupRadioFemale = "//input[@value='1']"
SignupUsernameInputBox = "//*[@id='root']/div/div/div[2]/div/div/div[2]/div[2]/div/form/div[3]/div/div"
SignupPasswordInputBox = "//*[@id='root']/div/div/div[2]/div/div/div[2]/div[2]/div/form/div[4]/div/div"
SignupConfirmPasswordInputBox = "//*[@id='root']/div/div/div[2]/div/div/div[2]/div[2]/div/form/div[5]/div/div"
SignupButton = "//button[@type='submit' and @tabindex='0']"
#Product Page Locator

#Product Detail Locator
AddToCartButton = "(//button[contains(text(),'Thêm vào giỏ hàng')])[1]"
#Cart Locator
IncreaseQuantityButton = "//button[@class='MuiButtonBase-root MuiButton-root MuiButton-outlined MuiButton-outlinedPrimary MuiButton-sizeSmall MuiButton-outlinedSizeSmall MuiButtonGroup-grouped MuiButtonGroup-groupedHorizontal MuiButtonGroup-groupedOutlined MuiButtonGroup-groupedOutlinedHorizontal MuiButtonGroup-groupedOutlinedPrimary MuiButton-root MuiButton-outlined MuiButton-outlinedPrimary MuiButton-sizeSmall MuiButton-outlinedSizeSmall MuiButtonGroup-grouped MuiButtonGroup-groupedHorizontal MuiButtonGroup-groupedOutlined MuiButtonGroup-groupedOutlinedHorizontal MuiButtonGroup-groupedOutlinedPrimary css-1ud4bu9-MuiButtonBase-root-MuiButton-root']"
QuantityValue = "//*[@id='root']/div/div[2]/div[2]/div/div[1]/div/table/tbody/tr/td[4]/div/button[2]"
RemoveButton = "//*[@id='root']/div/div[2]/div[2]/div/div[2]/div/button"
ConfirmButton = "//button[contains(text(), 'Xác nhận')]"
FirstProductCheckbox = "//*[@id='root']/div/div[2]/div[2]/div/div[1]/div/table/tbody/tr[1]"
SelectAllCheckbox = "//*[@id='root']/div/div[2]/div[2]/div/div[1]/div/table/thead/tr/th[1]/span"
CheckoutButton = "//*[@id='root']/div/div[2]/div[2]/div/div[2]/div/div/button"
#Checkout Locator
ChangeAddressButton = "//button[@class='MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeSmall MuiButton-containedSizeSmall MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeSmall MuiButton-containedSizeSmall css-1s6yt96-MuiButtonBase-root-MuiButton-root']"
CheckoutFullnameInputBox = "//*[@id=':rdrn:']"
CheckoutPhoneNumberInputBox = "//*[contains(text(),'Số điện thoại')]/following-sibling::*[1]/*"
CheckoutCityInputBox = "//*[contains(text(),'Tìm kiếm tỉnh, thành phố')]/following-sibling::*[1]/*"
Checkout1stOptionCombo = "//*[@id='tags-outlined-option-0']"
CheckoutDistrictInputBox = "//*[contains(text(),'Tìm kiếm quận, huyện')]/following-sibling::*[1]/*"
CheckoutWardInputBox = "//*[contains(text(),'Tìm kiếm phường, xã')]/following-sibling::*[1]/*"
CheckoutHomeAddressInputBox = "//*[contains(text(),'Số nhà, đường')]/following-sibling::*[1]/*"
ChangeShippingMethodButton = "//button[@class='MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium css-ygovoz-MuiButtonBase-root-MuiButton-root']"
FastShippingMethod = "//*[@id='ship-method-item-0']"
SlowShippingMethod = "//*[@id='ship-method-item-1']"
VoucherInputBox = "//*[contains(text(),'Mã giảm giá')]/following-sibling::*[1]/*"
ApplyButton = "//*[@id='root']/div/div[2]/div[2]/div/div[4]/div[2]/div[1]/div[2]/button"
TotalMoney = "//*[@id='root']/div/div[2]/div[2]/div/div[6]/div/div/div[3]/p[2]"
OrderButton = "//*[contains(text(),'Đặt hàng')]"

